from distutils.core import setup
setup(name='battlenet',
    version='0.1',
    py_modules=[
        'battlenet.constants',
        'battlenet.oauth.headers',
        'battlenet.oauth.oauth',
        'battlenet.oauth.profile',
        'battlenet.oauth.battletag',
        'battlenet.oauth.account',
        'battlenet.community.wow.achievements',
        'battlenet.community.wow.auctions',
        'battlenet.community.wow.battlepets',
        'battlenet.community.wow.challengemodes',
        'battlenet.community.wow.characters',
        'battlenet.community.wow.data',
        'battlenet.community.wow.guilds',
        'battlenet.community.wow.items',
        'battlenet.community.wow.pvp',
        'battlenet.community.wow.quests',
        'battlenet.community.wow.realms',
        'battlenet.community.wow.spells'
    ],
)